### PR TITLE
A more idiomatic use of `into` operator

### PR DESCRIPTION
**Pull request by pditommaso**

### CODE REVIEW

**Comment by thejmazz** [comment]
Thanks Paulo, I'll merge this soon and add an "edit" note

**Comment by thejmazz** [comment]
Oh, I did not realize this was the gsoc repo and not my blog. I'll make a not for myself to update from the blog side.

**Comment by pditommaso** [comment]
Is any action requested from me?

**Comment by bmpvieira** [comment]
Hi @pditommaso, sorry no action requested (this is already merged). Just doing some cleanup of https://github.com/orgs/bionode/projects/1 and putting a face on every issue to easily glance and see who did it. Thank you!

**Pull request merged**
